export const ERROR_CODES = {
  ALREADY_EXISTS: 'ALREDY_EXISTS',
  FOREIGN_CONSTRAINTS: 'FOREIGN_CONSTRAINTS',
  UNKNOWN: 'UNKNOWN',
  AUTH_LOCKED: 'AUTH_LOCKED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  LOGIN_FAILED: 'LOGINFAILED',
  AUTH_EXCHANGE_FAILED: 'AUTH_EXCHANGE_FAILED',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  DATABASE_RELATIONSHIP_CONSTRAINTS: 'DATABASE_RELATIONSHIP_CONSTRAINTS',
};
