version: '3.7'
services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq:/data
    ports:
      - '8080:80' # exposes ui ports
      - '5341:5341' # handles ingestion http end-point
    image: 'datalust/seq:latest'
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env.mongo
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres # configure postgres
    volumes:
      - authdb-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  rcli:
    image: redis:latest
    links:
      - redis
    command: redis-cli -h redis
volumes:
  authdb-data: # named volumes can be managed easier using docker-compose
  seq:
